**Statistiques textuelles**

In [78]:
import os
import pandas as pd
from string import punctuation
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
stopw = stopwords.words('english') + [x.translate
    (str.maketrans('', '', punctuation)) for x in stopwords.words('english')]

from collections import Counter

Corpus d'apprentissage

In [79]:
folder = '../2-scripts/1-preprocessing/'
datasets = os.listdir(folder)

stat_descriptives = []
for file in datasets:
    df = pd.read_excel(os.path.join(folder, file))
    data_all = df['cleaned_text_post'].astype('str').tolist()
    data_incels = df[df['category'] == 'incel']['cleaned_text_post'].astype('str').tolist()
    data_neutrals = df[df['category'] == 'neutral']['cleaned_text_post'].astype('str').tolist()

    tokens_all = [token for token in word_tokenize(' '.join(data_all)) if token not in punctuation]
    tokens_incels = [token for token in word_tokenize(' '.join(data_incels)) if token not in punctuation]
    tokens_neutrals = [token for token in word_tokenize(' '.join(data_neutrals)) if token not in punctuation]

    types_all = list(set(tokens_all))
    types_incels = list(set(tokens_incels))
    types_neutrals = list(set(tokens_neutrals))

    stat_descriptives.append(
            {
                'phase' : 'training',
                'nb_posts_total' : len(df),
                'nb_posts_incels' : len(data_incels),
                'nb_posts_neutrals' : len(data_neutrals),
                '% Incels' : int(file[22:-7]),
                'tokens (all)' : len(tokens_all),
                'types (all)' : len(types_all),
                'type-token ratio (all)' : len(types_all) / len(tokens_all) * 100,
                'tokens (incels)' : len(tokens_incels),
                'types (incels)' : len(types_incels),
                'type-token ratio (incels)' : len(types_incels) / len(tokens_incels) * 100,
                'tokens (neutrals)' : len(tokens_neutrals),
                'types (neutrals)' : len(types_neutrals),
                'type-token ratio (neutrals)' : len(types_neutrals) / len(tokens_neutrals) * 100,    
            }
    )

pd.DataFrame(stat_descriptives)

,phase,nb_posts_total,nb_posts_incels,nb_posts_neutrals,% Incels,tokens (all),types (all),type-token ratio (all),tokens (incels),types (incels),type-token ratio (incels),tokens (neutrals),types (neutrals),type-token ratio (neutrals)
0,training,40000,4000,36000,10,1087228,66037,6.073887,135121,11285,8.351774,952107,62930,6.609551
1,training,40000,8000,32000,20,1117519,63960,5.723393,270937,17064,6.298143,846582,57720,6.818005
2,training,40000,12000,28000,30,1156716,63543,5.493397,411506,21701,5.273556,745210,54381,7.297406
3,training,40000,16000,24000,40,1167474,60345,5.168852,547593,25747,4.701850,619881,48008,7.744712
4,training,40000,20000,20000,50,1214857,59124,4.866746,684798,29530,4.312221,530059,43425,8.192484
5,training,40000,24000,16000,60,1238734,56267,4.542299,816565,32243,3.948614,422169,37559,8.896674
6,training,40000,28000,12000,70,1259718,53694,4.262383,951361,35648,3.747053,308357,30900,10.020852
7,training,40000,32000,8000,80,1302462,50446,3.873126,1095336,39004,3.560916,207126,22959,11.084557
8,training,40000,36000,4000,90,1330756,48180,3.620498,1225100,42119,3.438005,105656,14767,13.976490

Corpus test

In [81]:
df = pd.read_excel('../1-data/cleaned_test_dataset_10pc.xlsx')

data_all = df['cleaned_text_post'].astype('str').tolist()
data_incels = df[df['category'] == 'incel']['cleaned_text_post'].astype('str').tolist()
data_neutrals = df[df['category'] == 'neutral']['cleaned_text_post'].astype('str').tolist()

tokens_all = [token for token in word_tokenize(' '.join(data_all)) if token not in punctuation]
tokens_incels = [token for token in word_tokenize(' '.join(data_incels)) if token not in punctuation]
tokens_neutrals = [token for token in word_tokenize(' '.join(data_neutrals)) if token not in punctuation]

types_all = list(set(tokens_all))
types_incels = list(set(tokens_incels))
types_neutrals = list(set(tokens_neutrals))

stat_descriptives.append(
        {
            'phase' : 'test',
            'nb_posts_total' : len(df),
            'nb_posts_incels' : len(data_incels),
            'nb_posts_neutrals' : len(data_neutrals),
            '% Incels' : 10,
            'tokens (all)' : len(tokens_all),
            'types (all)' : len(types_all),
            'type-token ratio (all)' : len(types_all) / len(tokens_all) * 100,
            'tokens (incels)' : len(tokens_incels),
            'types (incels)' : len(types_incels),
            'type-token ratio (incels)' : len(types_incels) / len(tokens_incels) * 100,
            'tokens (neutrals)' : len(tokens_neutrals),
            'types (neutrals)' : len(types_neutrals),
            'type-token ratio (neutrals)' : len(types_neutrals) / len(tokens_neutrals) * 100,    
        }
)

stat_descriptives = pd.DataFrame(stat_descriptives)
stat_descriptives

,phase,nb_posts_total,nb_posts_incels,nb_posts_neutrals,% Incels,tokens (all),types (all),type-token ratio (all),tokens (incels),types (incels),type-token ratio (incels),tokens (neutrals),types (neutrals),type-token ratio (neutrals)
0,training,40000,4000,36000,10,1087228,66037,6.073887,135121,11285,8.351774,952107,62930,6.609551
1,training,40000,8000,32000,20,1117519,63960,5.723393,270937,17064,6.298143,846582,57720,6.818005
2,training,40000,12000,28000,30,1156716,63543,5.493397,411506,21701,5.273556,745210,54381,7.297406
3,training,40000,16000,24000,40,1167474,60345,5.168852,547593,25747,4.701850,619881,48008,7.744712
4,training,40000,20000,20000,50,1214857,59124,4.866746,684798,29530,4.312221,530059,43425,8.192484
5,training,40000,24000,16000,60,1238734,56267,4.542299,816565,32243,3.948614,422169,37559,8.896674
6,training,40000,28000,12000,70,1259718,53694,4.262383,951361,35648,3.747053,308357,30900,10.020852
7,training,40000,32000,8000,80,1302462,50446,3.873126,1095336,39004,3.560916,207126,22959,11.084557
8,training,40000,36000,4000,90,1330756,48180,3.620498,1225100,42119,3.438005,105656,14767,13.976490
9,test,20000,2000,18000,10,529238,41484,7.838439,67824,7406,10.919439,461414,39554,8.572345

In [83]:
stat_descriptives.to_csv('../1-data/stat_descriptives_corpus.csv', index=False)